# Generated by Django 5.0.6 on 2024-07-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(default='', upload_to='cadidato'),
            preserve_default=False,
        ),
    ]
