# Generated by Django 5.0.6 on 2024-07-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_candidato_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista',
            old_name='logo',
            new_name='propuestas',
        ),
    ]
