# Generated by Django 5.0.6 on 2024-07-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_rename_logo_lista_propuestas'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='foto',
            field=models.ImageField(default='', upload_to='lista'),
            preserve_default=False,
        ),
    ]
