# Generated by Django 5.0.6 on 2024-07-09 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nulo', models.BooleanField(default=False)),
                ('blanco', models.BooleanField(default=False)),
                ('voto_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.lista')),
            ],
        ),
    ]
