# Generated by Django 5.0.6 on 2024-07-17 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_rename_logo_lista_propuestas'),
        ('voto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='voto_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.candidato'),
        ),
    ]
