# Generated by Django 5.0.6 on 2024-07-17 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_remove_estudiante_apellidos_remove_estudiante_cedula_and_more'),
        ('voto', '0002_alter_voto_voto_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='voto_de',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante'),
            preserve_default=False,
        ),
    ]
