# Generated by Django 5.0.6 on 2024-07-18 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voto', '0003_voto_voto_de'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='numero',
        ),
    ]
